
[[constraint]]
  branch = "master"
  name = "github.com/bitrise-io/bitrise-init"

[[constraint]]
  branch = "master"
  name = "github.com/bitrise-io/go-utils"

[[constraint]]
  branch = "master"
  name = "github.com/bitrise-io/go-xamarin"

[[constraint]]
  branch = "master"
  name = "github.com/bitrise-io/go-xcode"

[[constraint]]
  branch = "master"
  name = "github.com/bitrise-io/goinp"

[[constraint]]
  branch = "master"
  name = "github.com/bitrise-io/xcode-project"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.1"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.4"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.3.0"

# Could not introduce github.com/bitrise-io/go-xcode@master, as it has a
# dependency on github.com/ryanuber/go-glob with constraint ^1.0.0, which
# has no overlap with existing constraint master from github.com/bitrise-io/bitrise@1.31.0
[[override]]
  name = "github.com/ryanuber/go-glob"
  version = "1.0.0"

[prune]
  go-tests = true
  unused-packages = true
